name: Test

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * 2,6'
  push:
    paths:
      - '**.py'
      - '**.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tests

    steps:
      - name: 'Git – checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # - name: 'Git – setup submodules'
      #   run: |
      #     # cd weighted-list
      #     git submodule update --init --remote
      #     # cd ..

      - name: 'Python – setup'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Python – install'
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: 'Pytest – run'
        run: python3 -m pytest
